### ISSUE TITLE
Error! code - 20 does not exist!

### ISSUE THREAD

**Issue by daweedm** [stuicey/SSHy#4] opened 2018-05-04 20:42 UTC
I'm trying to make it work with websockify.
Since websockify does not support base64 flow since v0.5, I have tried the following changes in your code : 
```javascript
// Opens the websocket!
ws = new WebSocket(wsproxyURL);
ws.binaryType = "arraybuffer";
```
```javascript
// Send all recieved messages to SSHyClient.Transport.handle()
ws.onmessage = function(e) {
	// ArrayBuffer to String
	var enc = new TextDecoder("utf-8");
	var clearMessage = enc.decode(e.data);
	console.log(clearMessage);
	transport.parceler.handle(clearMessage);
};
```
```javascript
ws.sendB64 = function(e){
	var enc = new TextEncoder();
	this.send(enc.encode(e)); // String to ArrayBuffer conversion
	console.log("sendB64", e);
	
	transport.parceler.transmitData += e.length;
	transport.settings.setNetTraffic(transport.parceler.transmitData, false);
};
```

I'm getting the following logs in the console :
```bash
SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u3
```
```bash
SSH-2.0-SSHyClient
```
```bash
T<=òDÞ¸Þ'B9¹diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha256,diffie-hellman-group1-sha1ssh-rsa
aes128-ctr
aes128-ctrhmac-sha2-256,hmac-sha1hmac-sha2-256,hmac-sha1nonenone
```
```bash
4�h�v����uha+Q+��curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1Assh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519lchacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.comlchacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com�umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1�umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1none,zlib@openssh.comnone,zlib@openssh.com
```
```bash
Chosen Algs = kex=diffie-hellman-group-exchange-sha256, keys=ssh-rsa, cipher=aes128-ctr, mac=undefined
```
```bash
Error! code - 20 does not exist!
```

Then the websockets closes. What does `Error! code - 20 does not exist!` mean ?

Many thanks !

**Comment by stuicey** [comment] 2018-05-04 22:36
That error seems to be a bit of a red herring as byte code 20 (`SSH_MSG_KEXINIT`) is a handled byte code as it signals the initialisation of the key exchange process. It seems your issue is within that process where the client is choosing which algorithms to use. The debugging message `Chosesn Algs = ... ` has the hmac algorithm undefined which is causing the connection to immediately be closed as it is required to complete key exchange. 

Regardless the error is odd as you should have a matching pair at `hmac-sha2-256` from the data above: 
```
> client='hmac-sha2-256,hmac-sha1'
> server='umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1'
> filter(client,server)
"hmac-sha2-256"
```
The filter function is defined [here](https://github.com/stuicey/SSHy/blob/master/js/src/utilities.min.js#L80), I would suggest modifying it to log both client and server and verify the correct data is being passed to the function and that it is matching properly.

Hopefully this helps, keep me updated I'm curious what the issue is.

**Comment by stuicey** [comment] 2018-05-13 19:30
Closing due to inactivity.

**Closed by stuicey** 2018-05-13 19:30 UTC

**Comment by royzhao7** [comment] 2024-12-17 08:18
f you have control over the SSH server and want to enable ssh-rsa support, you can modify the server's SSH configuration.

Edit the SSHD Config File:
Open the SSH daemon configuration file (usually located at /etc/ssh/sshd_config):

`sudo nano /etc/ssh/sshd_config`
Add or Modify the Following Line:

`HostKeyAlgorithms +ssh-rsa`
Restart the SSH Service: After making changes, restart the SSH service to apply them:

`sudo systemctl restart sshd          `    this solution works for me
